name: workflow
on: push
jobs:
  job:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell:  bash
    steps:
    - name: "sudo npm make"
      run:  sudo npm install make

    - name: "sudo npm link"
      run:  sudo npm link

    - name: "make lint"
      run:  make lint
