name: workflow
on: push
jobs:
  job:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell:  bash
    steps:
    - name: "sudo npm make"
      run:  sudo npm install make
    
    - name: "publish"
      run:  npm publish --dry-run
      
    - name: "make lint"
      run:  make lint
